FROM python:3.10-slim
WORKDIR /app
RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/JoeLacht/-simple_streamlit.git
WORKDIR /app/-simple_streamlit
RUN pip install -r requirements.txt
EXPOSE 8502
HEALTHCHECK CMD curl --fail http://localhost:8502/_stcore/health
ENTRYPOINT ["streamlit", "run", "Apple.py", "--server.port=8502", "--server.address=0.0.0.0"]